---
- name: Converge
  hosts: miniweb
  become: true
  gather_facts: true
  tasks:
    - name: "Include miniweb role"
      include_role:
        name: "miniweb"
#    - name: "Include mariadb role"
#      include_role:
#        name: "mariadb"