---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
  yamllint -c molecule/tests/yamllint.yml .
  ansible-lint -v -c molecule/tests/lint.yml .

platforms:
  - name: Miniweb-Ubuntu1804
    groups:
      - miniweb
    hostname: miniweb-u18
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    network_mode: bridge  # bridge, none, container: foo, host
    published_ports:
      - 8080:80
    privileged: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    environment:
      container: docker
    pre_build_image: true
  - name: Miniweb-Ubuntu2004
    hostname: miniweb-u20
    network_mode: bridge  # bridge, none, container: foo, host
    published_ports:
      - 8081:80
    groups:
      - miniweb
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    privileged: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
    environment:
      container: docker

provisioner:
  name: ansible
  lint:
    name: |
      yamllint -c molecule/tests/yamllint.yml .
      ansible-lint -v -c molecule/tests/lint.yml .

verifier:
  #name: ansible
  name: testinfra
  lint:
    name: flake8
  options:
    sudo: true
    v: 1
  directory: ../tests


# Default scenario! Optional.
scenario:
  create_sequence:
    - dependency # not configured yet.
    - create
    - prepare
  check_sequence:
    - dependency # not configured yet.
    #- cleanup # not configured yet.
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency # not configured yet.
    - lint
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency # not configured yet.
    - cleanup # not configured yet.
    - destroy
  test_sequence:
    - dependency # not configured yet.
    - lint
    #- cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect # not configured yet.
    - verify
    #- cleanup # not configured yet.
    - destroy